// This was generated by codegen script.

const std = @import("std");
const testing = std.testing;

test "absolute_layout_within_border" {
    const S = @import("stretch");
    var stretch = try S.Stretch.new(std.testing.allocator);
    defer stretch.deinit();

    var node_1_style = S.Style.default();
    node_1_style.position_type = S.PositionType.Absolute;
    node_1_style.size.width = S.Dimension{ .Points = 50.0 };
    node_1_style.size.height = S.Dimension{ .Points = 50.0 };
    node_1_style.position.start = S.Dimension{ .Points = 0.0 };
    node_1_style.position.top = S.Dimension{ .Points = 0.0 };

    const node_1 = try stretch.new_node(node_1_style, &[_]S.Node{});

    var node_2_style = S.Style.default();
    node_2_style.position_type = S.PositionType.Absolute;
    node_2_style.size.width = S.Dimension{ .Points = 50.0 };
    node_2_style.size.height = S.Dimension{ .Points = 50.0 };
    node_2_style.position.end = S.Dimension{ .Points = 0.0 };
    node_2_style.position.bottom = S.Dimension{ .Points = 0.0 };

    const node_2 = try stretch.new_node(node_2_style, &[_]S.Node{});

    var node_3_style = S.Style.default();
    node_3_style.position_type = S.PositionType.Absolute;
    node_3_style.size.width = S.Dimension{ .Points = 50.0 };
    node_3_style.size.height = S.Dimension{ .Points = 50.0 };
    node_3_style.margin.start = S.Dimension{ .Points = 10.0 };
    node_3_style.margin.end = S.Dimension{ .Points = 10.0 };
    node_3_style.margin.top = S.Dimension{ .Points = 10.0 };
    node_3_style.margin.bottom = S.Dimension{ .Points = 10.0 };
    node_3_style.position.start = S.Dimension{ .Points = 0.0 };
    node_3_style.position.top = S.Dimension{ .Points = 0.0 };

    const node_3 = try stretch.new_node(node_3_style, &[_]S.Node{});

    var node_4_style = S.Style.default();
    node_4_style.position_type = S.PositionType.Absolute;
    node_4_style.size.width = S.Dimension{ .Points = 50.0 };
    node_4_style.size.height = S.Dimension{ .Points = 50.0 };
    node_4_style.margin.start = S.Dimension{ .Points = 10.0 };
    node_4_style.margin.end = S.Dimension{ .Points = 10.0 };
    node_4_style.margin.top = S.Dimension{ .Points = 10.0 };
    node_4_style.margin.bottom = S.Dimension{ .Points = 10.0 };
    node_4_style.position.end = S.Dimension{ .Points = 0.0 };
    node_4_style.position.bottom = S.Dimension{ .Points = 0.0 };

    const node_4 = try stretch.new_node(node_4_style, &[_]S.Node{});

    var node_style = S.Style.default();
    node_style.size.width = S.Dimension{ .Points = 100.0 };
    node_style.size.height = S.Dimension{ .Points = 100.0 };
    node_style.padding.start = S.Dimension{ .Points = 10.0 };
    node_style.padding.end = S.Dimension{ .Points = 10.0 };
    node_style.padding.top = S.Dimension{ .Points = 10.0 };
    node_style.padding.bottom = S.Dimension{ .Points = 10.0 };
    node_style.border.start = S.Dimension{ .Points = 10.0 };
    node_style.border.end = S.Dimension{ .Points = 10.0 };
    node_style.border.top = S.Dimension{ .Points = 10.0 };
    node_style.border.bottom = S.Dimension{ .Points = 10.0 };

    const node = try stretch.new_node(node_style, &[_]S.Node{ node_1, node_2, node_3, node_4 });

    try stretch.compute_layout(node, S.UndefinedSize());

    const node_layout = try stretch.layout(node);
    try std.testing.expect(node_layout.size.width == 100.0);
    try std.testing.expect(node_layout.size.height == 100.0);
    try std.testing.expect(node_layout.location.x == 0.0);
    try std.testing.expect(node_layout.location.y == 0.0);

    const node_1_layout = try stretch.layout(node_1);
    try std.testing.expect(node_1_layout.size.width == 50.0);
    try std.testing.expect(node_1_layout.size.height == 50.0);
    try std.testing.expect(node_1_layout.location.x == 10.0);
    try std.testing.expect(node_1_layout.location.y == 10.0);

    const node_2_layout = try stretch.layout(node_2);
    try std.testing.expect(node_2_layout.size.width == 50.0);
    try std.testing.expect(node_2_layout.size.height == 50.0);
    try std.testing.expect(node_2_layout.location.x == 40.0);
    try std.testing.expect(node_2_layout.location.y == 40.0);

    const node_3_layout = try stretch.layout(node_3);
    try std.testing.expect(node_3_layout.size.width == 50.0);
    try std.testing.expect(node_3_layout.size.height == 50.0);
    try std.testing.expect(node_3_layout.location.x == 20.0);
    try std.testing.expect(node_3_layout.location.y == 20.0);

    const node_4_layout = try stretch.layout(node_4);
    try std.testing.expect(node_4_layout.size.width == 50.0);
    try std.testing.expect(node_4_layout.size.height == 50.0);
    try std.testing.expect(node_4_layout.location.x == 30.0);
    try std.testing.expect(node_4_layout.location.y == 30.0);
}
