// This was generated by codegen script.

const std = @import("std");
const testing = std.testing;

test "percentage_size_based_on_parent_inner_size" {
    const S = @import("stretch");
    var stretch = try S.Stretch.new(std.testing.allocator);
    defer stretch.deinit();

    var node_1_style = S.Style.default();
    node_1_style.size.width = S.Dimension{ .Percent = 0.5 };
    node_1_style.size.height = S.Dimension{ .Percent = 0.5 };

    const node_1 = try stretch.new_node(node_1_style, &[_]S.Node{});

    var node_style = S.Style.default();
    node_style.flex_direction = S.FlexDirection.Column;
    node_style.size.width = S.Dimension{ .Points = 200.0 };
    node_style.size.height = S.Dimension{ .Points = 400.0 };
    node_style.padding.start = S.Dimension{ .Points = 20.0 };
    node_style.padding.end = S.Dimension{ .Points = 20.0 };
    node_style.padding.top = S.Dimension{ .Points = 20.0 };
    node_style.padding.bottom = S.Dimension{ .Points = 20.0 };

    const node = try stretch.new_node(node_style, &[_]S.Node{node_1});

    try stretch.compute_layout(node, S.UndefinedSize());

    const node_layout = try stretch.layout(node);
    try std.testing.expect(node_layout.size.width == 200.0);
    try std.testing.expect(node_layout.size.height == 400.0);
    try std.testing.expect(node_layout.location.x == 0.0);
    try std.testing.expect(node_layout.location.y == 0.0);

    const node_1_layout = try stretch.layout(node_1);
    try std.testing.expect(node_1_layout.size.width == 80.0);
    try std.testing.expect(node_1_layout.size.height == 180.0);
    try std.testing.expect(node_1_layout.location.x == 20.0);
    try std.testing.expect(node_1_layout.location.y == 20.0);
}
