// This was generated by codegen script.

const std = @import("std");
const testing = std.testing;

test "wrapped_column_max_height" {
    const S = @import("stretch");
    var stretch = try S.Stretch.new(std.testing.allocator);
    defer stretch.deinit();

    var node_1_style = S.Style.default();
    node_1_style.size.width = S.Dimension{ .Points = 100.0 };
    node_1_style.size.height = S.Dimension{ .Points = 500.0 };
    node_1_style.max_size.height = S.Dimension{ .Points = 200.0 };

    const node_1 = try stretch.new_node(node_1_style, &[_]S.Node{});

    var node_2_style = S.Style.default();
    node_2_style.size.width = S.Dimension{ .Points = 200.0 };
    node_2_style.size.height = S.Dimension{ .Points = 200.0 };
    node_2_style.margin.start = S.Dimension{ .Points = 20.0 };
    node_2_style.margin.end = S.Dimension{ .Points = 20.0 };
    node_2_style.margin.top = S.Dimension{ .Points = 20.0 };
    node_2_style.margin.bottom = S.Dimension{ .Points = 20.0 };

    const node_2 = try stretch.new_node(node_2_style, &[_]S.Node{});

    var node_3_style = S.Style.default();
    node_3_style.size.width = S.Dimension{ .Points = 100.0 };
    node_3_style.size.height = S.Dimension{ .Points = 100.0 };

    const node_3 = try stretch.new_node(node_3_style, &[_]S.Node{});

    var node_style = S.Style.default();
    node_style.flex_direction = S.FlexDirection.Column;
    node_style.flex_wrap = S.FlexWrap.Wrap;
    node_style.align_items = S.AlignItems.Center;
    node_style.align_content = S.AlignContent.Center;
    node_style.justify_content = S.JustifyContent.Center;
    node_style.size.width = S.Dimension{ .Points = 700.0 };
    node_style.size.height = S.Dimension{ .Points = 500.0 };

    const node = try stretch.new_node(node_style, &[_]S.Node{ node_1, node_2, node_3 });

    try stretch.compute_layout(node, S.UndefinedSize());

    const node_layout = try stretch.layout(node);
    try std.testing.expect(node_layout.size.width == 700.0);
    try std.testing.expect(node_layout.size.height == 500.0);
    try std.testing.expect(node_layout.location.x == 0.0);
    try std.testing.expect(node_layout.location.y == 0.0);

    const node_1_layout = try stretch.layout(node_1);
    try std.testing.expect(node_1_layout.size.width == 100.0);
    try std.testing.expect(node_1_layout.size.height == 200.0);
    try std.testing.expect(node_1_layout.location.x == 250.0);
    try std.testing.expect(node_1_layout.location.y == 30.0);

    const node_2_layout = try stretch.layout(node_2);
    try std.testing.expect(node_2_layout.size.width == 200.0);
    try std.testing.expect(node_2_layout.size.height == 200.0);
    try std.testing.expect(node_2_layout.location.x == 200.0);
    try std.testing.expect(node_2_layout.location.y == 250.0);

    const node_3_layout = try stretch.layout(node_3);
    try std.testing.expect(node_3_layout.size.width == 100.0);
    try std.testing.expect(node_3_layout.size.height == 100.0);
    try std.testing.expect(node_3_layout.location.x == 420.0);
    try std.testing.expect(node_3_layout.location.y == 200.0);
}
